[package]
name = "mkplaylist"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.3"
rand = "0.8"
rusqlite = { version = "0.25", features = [ "bundled" ] }
